Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2023-01, with the labels that each got.

#28 Improve the elements interface
  README.md
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/dgs.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/loads/tests/test_loads.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/tests/test_phases.py
Labels: enhancement

#33 Make `net.res_buses_voltages` a property
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#36 Transformer phases update
  roseau/load_flow/io/dict.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/tests/data/networks/mv_lv_transformers/network_impedance.json
  roseau/load_flow/tests/data/networks/mv_lv_transformers/network_power.json
  roseau/load_flow/tests/test_phases.py
Labels: enhancement

#37 Add tests for the v0 to v1 converter so it doesn't go out of sync
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
Labels: enhancement

#39 Small fixes
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_phases.py
Labels: bug

#40 Floating neutrals in loads and sources do not work yet
  roseau/load_flow/io/tests/test_dgs.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/tests/test_phases.py
Labels: bug

#41 Only build conda package on the main branch
  .github/workflows/conda.yml
Labels: enhancement

#42 Fix failing doc builds
  .github/workflows/doc.yml
Labels: bug, documentation

#44 Elements are aware of the network
  roseau/__init__.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#43 Add a method to get the powers of the loads
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/loads/tests/test_loads.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_phases.py
Labels: enhancement

#45 Separate models from core to break import cycles
  roseau/load_flow/models/__init__.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/transformers/transformers.py
Labels: enhancement

#46 Miscellaneous improvements
  roseau/load_flow/exceptions.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/lines/tests/test_parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/typing.py
  roseau/load_flow/utils/mixins.py
  roseau/load_flow/utils/types.py
Labels: enhancement

#47 Fix `res_voltages` and make voltage calculation public
  roseau/load_flow/converters.py
  roseau/load_flow/io/dgs.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/loads/tests/__init__.py
  roseau/load_flow/models/tests/__init__.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/tests/test_phases.py
  roseau/load_flow/models/tests/test_switch.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/tests/__init__.py
  roseau/load_flow/models/voltage_sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_converters.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/units.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/constants.py
Labels: bug, enhancement

#48 Return results of ground potential and pref current
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#50 Make `connected_elements` private
  roseau/load_flow/io/dict.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/network.py
Labels: enhancement
