Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2023-02, with the labels that each got.

#52 Fix default phases for lines where the second becomes 'ac'
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/tests/test_phases.py
Labels: bug

#54 Fix network results missing some keys
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: bug

#55 Compatibility with the server
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#56 Rename voltage_source(s) to source(s)
  README.md
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/__init__.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#58 Warm start argument to `solve_load_flow`
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#59 Improve installations docs and API reference
  README.md
  doc/conf.py
  doc/index.md
  doc/installation.md
  roseau/load_flow/__init__.py
  roseau/load_flow/converters.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/__init__.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/__init__.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/typing.py
  roseau/load_flow/units.py
  roseau/load_flow/utils/__init__.py
Labels: documentation

#60 Units for public methods
  poetry.lock
  pyproject.toml
  roseau/load_flow/__about__.py
  roseau/load_flow/__init__.py
  roseau/load_flow/converters.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_branches.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_lines.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_converters.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/units.py
  roseau/load_flow/utils/mixins.py
Labels: enhancement

#64 Some improvements
  README.md
  roseau/load_flow/io/dgs.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/typing.py
Labels: bug, enhancement

#62 Update the tutorials
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .vscode/cspell.json
  README.md
  doc/_static/Advanced_Tutorial.svg
  doc/_static/Control_PU_Cons.png
  doc/_static/Control_PU_Cons.svg
  doc/_static/Control_PU_Prod.png
  doc/_static/Control_PU_Prod.svg
  doc/_static/Control_QU.png
  doc/_static/Control_QU.svg
  doc/_static/Getting_Started_Tutorial.svg
  doc/_static/Logo_Roseau_Technologies_Without_Baseline.png
  doc/_static/Logo_Roseau_Technologies_Without_Baseline.svg
  doc/conf.py
  doc/index.md
  doc/notebooks/Advanced.ipynb
  doc/notebooks/Getting_Started.ipynb
  doc/notebooks/IO.ipynb
  poetry.lock
  pyproject.toml
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/dgs.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_flexible_parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/typing.py
  roseau/load_flow/units.py
Labels: documentation

#65 Final pass on the documentation
  .gitattributes
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  doc/conf.py
  doc/index.md
  doc/installation.md
  doc/notebooks/Advanced.ipynb
  doc/notebooks/Getting_Started.ipynb
  poetry.lock
  pyproject.toml
  roseau/load_flow/exceptions.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_flexible_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/typing.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/constants.py
  roseau/load_flow/utils/mixins.py
  roseau/load_flow/utils/types.py
Labels: documentation

#72 DOC: LaTeX images
  .gitignore
  README.md
  conda/meta.yaml
  doc/_static/Constant_P_Projection.svg
  doc/_static/Constant_P_Projection.tex
  doc/_static/Constant_Q_Projection.svg
  doc/_static/Constant_Q_Projection.tex
  doc/_static/Control_PU_Cons.svg
  doc/_static/Control_PU_Cons.tex
  doc/_static/Control_PU_Prod.svg
  doc/_static/Control_PU_Prod.tex
  doc/_static/Control_QU.svg
  doc/_static/Control_QU.tex
  doc/_static/Control_Trajectory_PmaxU_QU.svg
  doc/_static/Control_Trajectory_PmaxU_QU.tex
  doc/_static/Definitions.tex
  doc/_static/Delta_Connection.svg
  doc/_static/Delta_Connection.tex
  doc/_static/Domain_Common.tikz
  doc/_static/Domain_Pconst_QU_Eucl.svg
  doc/_static/Domain_Pconst_QU_Eucl.tex
  doc/_static/Domain_Pconst_QU_P.svg
  doc/_static/Domain_Pconst_QU_P.tex
  doc/_static/Domain_Pconst_QU_Q.svg
  doc/_static/Domain_Pconst_QU_Q.tex
  doc/_static/Domain_Pconst_Qconst.svg
  doc/_static/Domain_Pconst_Qconst.tex
  doc/_static/Domain_PmaxU_QU.svg
  doc/_static/Domain_PmaxU_QU.tex
  doc/_static/Domain_PmaxU_Qconst.svg
  doc/_static/Domain_PmaxU_Qconst.tex
  doc/_static/Euclidean_Projection.svg
  doc/_static/Euclidean_Projection.tex
  doc/_static/Makefile
  doc/_static/Star_Connection.svg
  doc/_static/Star_Connection.tex
  doc/conf.py
  doc/index.md
  doc/notebooks/Advanced.ipynb
  doc/notebooks/Getting_Started.ipynb
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
Labels: documentation
