Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2023-08, with the labels that each got.

#108 Documentation fixes
  doc/_static/css/custom.css
  doc/_static/css/notebooks.css
  doc/conf.py
  doc/notebooks/Getting_Started.ipynb
Labels: documentation

#110 Temporarily disable problematic link in the docs
  doc/index.md
Labels: documentation

#113 Error when accessing results of disconnected elements
  doc/Changelog.md
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
Labels: bug

#114 Update pint minimal requirement
  conda/environment.yml
  conda/meta.yaml
  doc/Changelog.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/units.py
Labels: enhancement

#115 Reformat tutorials and delete docker
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/doc.yml
  Dockerfile
  README.md
  doc/Changelog.md
  doc/Installation.md
  doc/_static/2022_10_20_Installation_1.png
  doc/_static/2022_10_20_Installation_2.png
  doc/_static/2022_10_20_Installation_3.png
  doc/_static/2022_10_20_Installation_4.png
  doc/_static/2022_10_20_Installation_5.png
  doc/_static/2022_10_20_Installation_6.png
  doc/_static/Load/American_Star_Load.svg
  doc/_static/Transformer/Windings.svg
  doc/_static/Transformer/Windings_Dz0.svg
  doc/_static/Transformer/Windings_Yd5.svg
  doc/_static/css/notebooks.css
  doc/conf.py
  doc/images/Transformer/Windings_Common.tikz
  doc/index.md
  doc/models/Bus.md
  doc/models/Transformer/index.md
  doc/notebooks/Advanced.ipynb
  doc/notebooks/Getting_Started.ipynb
  doc/notebooks/Short_Circuit.ipynb
  doc/notebooks/data
  doc/notebooks/index.md
  doc/usage/Connecting_Elements.md
  doc/usage/Flexible_Loads.md
  doc/usage/Getting_Started.md
  doc/usage/Short_Circuit.md
  doc/usage/index.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/io/dgs.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/network.py
  scripts/network_files_upgrade.py
Labels: documentation, enhancement

#119 Add explicit error message for singular jacobian
  doc/Changelog.md
  roseau/load_flow/exceptions.py
Labels: enhancement

#123 Shorter github links in the changelog
  .pre-commit-config.yaml
  doc/Changelog.md
  doc/conf.py
Labels: documentation, enhancement
