Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-10, with the labels that each got.

#270 Use Rye intead of Poetry
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  doc/Changelog.md
  poetry.lock
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  roseau/load_flow/models/buses.py
Labels: enhancement, dependencies

#272 Fix segfault when phases of pref are not the same as the bus
  doc/Changelog.md
  roseau/load_flow/models/potential_refs.py
Labels: bug

#273 Dynamically calculate the stacklevel of the first frame outside of `roseau.load_flow` for warnings
  doc/Changelog.md
  roseau/load_flow/io/dgs/__init__.py
  roseau/load_flow/io/dgs/lines.py
  roseau/load_flow/io/dgs/switches.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/network.py
  roseau/load_flow/utils/_exceptions.py
Labels: enhancement

#275 Use uv
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  doc/Changelog.md
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  uv.lock
Labels: dependencies

#276 Backward forward
  doc/Changelog.md
  doc/advanced/Solvers.md
  roseau/load_flow/_solvers.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_solvers.py
  roseau/load_flow/typing.py
Labels: enhancement
