Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-03, with the labels that each got.

#192 Optimize results
  doc/Changelog.md
  pyproject.toml
  roseau/load_flow/_wrapper.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_flexible_parameters.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
Labels: enhancement

#196 Small improvements to flexible loads
  doc/Changelog.md
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/typing.py
Labels: enhancement

#199 Update the transformers catalogue
  doc/Changelog.md
  doc/_static/Transformer/Minera-EcoDesign2021-20kV_ZZ6921.pdf
  doc/_static/Transformer/Trihal-EcoDesign2021-20kV_ZZ6925.pdf
  doc/_static/Transformer/Vegeta-EcoDesign2021-20kV_ZZ6924.pdf
  doc/usage/Catalogues.md
  roseau/load_flow/data/transformers/Catalogue.csv
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
Labels: enhancement

#201 Add load.type and rename branch.branch_type
  .vscode/cspell.json
  doc/Changelog.md
  doc/_static/Network/Catalogue.html
  doc/_static/Network/LVFeeder00939.html
  doc/_static/Network/LVFeeder02639.html
  doc/_static/Network/LVFeeder04790.html
  doc/_static/Network/LVFeeder06713.html
  doc/_static/Network/LVFeeder06926.html
  doc/_static/Network/LVFeeder06975.html
  doc/_static/Network/LVFeeder18498.html
  doc/_static/Network/LVFeeder18769.html
  doc/_static/Network/LVFeeder19558.html
  doc/_static/Network/LVFeeder20256.html
  doc/_static/Network/LVFeeder23832.html
  doc/_static/Network/LVFeeder24400.html
  doc/_static/Network/LVFeeder27429.html
  doc/_static/Network/LVFeeder27681.html
  doc/_static/Network/LVFeeder30216.html
  doc/_static/Network/LVFeeder31441.html
  doc/_static/Network/LVFeeder36284.html
  doc/_static/Network/LVFeeder36360.html
  doc/_static/Network/LVFeeder37263.html
  doc/_static/Network/LVFeeder38211.html
  doc/_static/Network/MVFeeder004.html
  doc/_static/Network/MVFeeder011.html
  doc/_static/Network/MVFeeder015.html
  doc/_static/Network/MVFeeder032.html
  doc/_static/Network/MVFeeder041.html
  doc/_static/Network/MVFeeder063.html
  doc/_static/Network/MVFeeder078.html
  doc/_static/Network/MVFeeder115.html
  doc/_static/Network/MVFeeder128.html
  doc/_static/Network/MVFeeder151.html
  doc/_static/Network/MVFeeder159.html
  doc/_static/Network/MVFeeder176.html
  doc/_static/Network/MVFeeder210.html
  doc/_static/Network/MVFeeder217.html
  doc/_static/Network/MVFeeder232.html
  doc/_static/Network/MVFeeder251.html
  doc/_static/Network/MVFeeder290.html
  doc/_static/Network/MVFeeder312.html
  doc/_static/Network/MVFeeder320.html
  doc/_static/Network/MVFeeder339.html
  doc/usage/Getting_Started.md
  doc/usage/Plotting.md
  doc/usage/Short_Circuit.md
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/types.py
  scripts/plot_network_catalogue.py
Labels: enhancement

#202 Explicitly prevent the instantiation of abstract classes
  doc/Changelog.md
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/tests/test_element.py
Labels: enhancement

#204 Remove restrictions on geometry types and allow custom CRS
  doc/Changelog.md
  roseau/load_flow/_solvers.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#205 Improve potentials propagation
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: bug, enhancement

#206 Un-deprecate results_to_dict and remove results_from_dict
  doc/Changelog.md
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/mixins.py
Labels: enhancement

#207 Transformer tests
  .pre-commit-config.yaml
  doc/Changelog.md
  doc/_static/Line/European_Shunt_Line.svg
  doc/conf.py
  doc/models/Transformer/Three_Phase_Transformer.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/models/transformers/transformers.py
Labels: bug
