Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-09, with the labels that each got.

#263 Accept folium.Map keywords in plot_interactive_map
  doc/Changelog.md
  roseau/load_flow/plotting.py
Labels: enhancement

#237 Sphinx configuration improvements
  .pre-commit-config.yaml
  doc/Changelog.md
  doc/advanced/index.md
  doc/conf.py
  doc/index.md
  doc/models/Bus.md
  doc/models/Ground.md
  doc/models/Line/index.md
  doc/models/Load/FlexibleLoad/index.md
  doc/models/Load/index.md
  doc/models/PotentialRef.md
  doc/models/Switch.md
  doc/models/Transformer/index.md
  doc/models/VoltageSource.md
  doc/models/index.md
  doc/usage/index.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/loads/flexible_parameters.py
Labels: documentation, enhancement

#267 Activate License in Google Colab
  doc/Changelog.md
  doc/License.md
  doc/_static/2024_09_16_Google_Colab_Environment_Variable.png
Labels: documentation
