Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-01, with the labels that each got.

#163 Fix res_transformers returning an empty dataframe
  doc/Changelog.md
  roseau/load_flow/network.py
Labels: bug

#164 Moving away from SaaS, step 1
  .github/workflows/ci.yml
  .github/workflows/doc.yml
  .pre-commit-config.yaml
  LICENSE.md
  README.md
  conda/environment.yml
  conda/meta.yaml
  doc/Installation.md
  doc/License.md
  doc/_static/2024_01_12_Pycharm_Console_Environment_Variable.png
  doc/conf.py
  doc/index.md
  doc/models/Bus.md
  doc/models/Ground.md
  doc/models/Line/ShuntLine.md
  doc/models/Line/SimplifiedLine.md
  doc/models/Load/CurrentLoad.md
  doc/models/Load/FlexibleLoad/FeasibleDomain.md
  doc/models/Load/ImpedanceLoad.md
  doc/models/Load/PowerLoad.md
  doc/models/Switch.md
  doc/models/Transformer/Three_Phase_Transformer.md
  doc/usage/Connecting_Elements.md
  doc/usage/Flexible_Loads.md
  doc/usage/Getting_Started.md
  doc/usage/Short_Circuit.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/__about__.py
  roseau/load_flow/__init__.py
  roseau/load_flow/_solvers.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/dgs.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/license.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/models/tests/test_flexible_parameters.py
  roseau/load_flow/models/tests/test_phases.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/solvers.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/tests/test_solvers.py
  roseau/load_flow/typing.py
  roseau/load_flow/utils/_versions.py
  roseau/load_flow/utils/log.py
Labels: enhancement

#165 Moving away from SaaS, step 2
  roseau/load_flow/converters.py
  roseau/load_flow/license.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/network.py
Labels: enhancement

#168 Potentials propagation
  doc/Changelog.md
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: bug, enhancement

#170 Add missing changelog entries
  doc/Changelog.md
Labels: documentation
