Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-07, with the labels that each got.

#233 Version 0.9.1
  .pre-commit-config.yaml
  .vscode/cspell.json
  doc/Changelog.md
  doc/conf.py
  doc/models/Line/Parameters.md
  doc/usage/Catalogues.md
  doc/usage/Connecting_Elements.md
  doc/usage/Data_Exchange.md
  doc/usage/Extras.md
  doc/usage/Flexible_Loads.md
  doc/usage/Getting_Started.md
  doc/usage/Plotting.md
  doc/usage/Short_Circuit.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/conftest.py
  roseau/load_flow/data/io/DGS-RLF.pfd
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/dgs.py
  roseau/load_flow/io/dgs/__init__.py
  roseau/load_flow/io/dgs/buses.py
  roseau/load_flow/io/dgs/constants.py
  roseau/load_flow/io/dgs/lines.py
  roseau/load_flow/io/dgs/loads.py
  roseau/load_flow/io/dgs/sources.py
  roseau/load_flow/io/dgs/switches.py
  roseau/load_flow/io/dgs/transformers.py
  roseau/load_flow/io/tests/test_dgs.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_flexible_parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/tests/data/dgs/Exemple_exhaustif.json
  roseau/load_flow/tests/data/dgs/LV_Line.json
  roseau/load_flow/tests/data/dgs/LV_network.json
  roseau/load_flow/tests/data/dgs/MV_LV_Transformer.json
  roseau/load_flow/tests/data/dgs/MV_LV_Transformer_LV_grid.json
  roseau/load_flow/tests/data/dgs/MV_LV_Transformer_unbalanced.json
  roseau/load_flow/tests/data/dgs/MV_Line.json
  roseau/load_flow/tests/data/dgs/MV_Network.json
  roseau/load_flow/tests/data/dgs/special/Gen_Stat.json
  roseau/load_flow/tests/data/dgs/special/General_Load.json
  roseau/load_flow/tests/data/dgs/special/LV_Load.json
  roseau/load_flow/tests/data/dgs/special/Line_Without_Type.json
  roseau/load_flow/tests/data/dgs/special/MV_Load.json
  roseau/load_flow/tests/data/dgs/special/PV_Sys.json
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/mixins.py
Labels: enhancement

#234 Docs: Fix links and improve license page
  doc/License.md
  doc/conf.py
  doc/usage/Data_Exchange.md
Labels: documentation

#240 Add tests for switches imported from DGS and improve warning and error messages
  .vscode/cspell.json
  doc/Changelog.md
  roseau/load_flow/io/dgs/constants.py
  roseau/load_flow/io/dgs/switches.py
  roseau/load_flow/io/tests/test_dgs.py
  roseau/load_flow/tests/data/dgs/special/Switch.json
Labels: enhancement

#241 Add tutorials
  tutorials/OpenDSS/README.md
  tutorials/OpenDSS/Tutorial_1/Exercise_1.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-Earth-Return.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-With-Neutral.ipynb
  tutorials/OpenDSS/images/LV_Network_With_Neutral.png
  tutorials/OpenDSS/images/LV_Network_Without_Neutral.png
  tutorials/OpenDSS/images/Star_Delta.png
  tutorials/OpenDSS/pyproject.toml
  tutorials/README.md
Labels: tutorials

#243 Minor DGS fixes and addition of some extra information
  doc/Changelog.md
  doc/_static/IO/DGS_Export_Window.png
  roseau/load_flow/io/dgs/constants.py
  roseau/load_flow/io/dgs/lines.py
  roseau/load_flow/io/dgs/transformers.py
Labels: bug

#245 Fix `LineParameters.from_geometry` with unknown insulation
  doc/Changelog.md
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/utils/constants.py
Labels: bug

#246 Fix converters and improve typing
  doc/Changelog.md
  roseau/load_flow/converters.py
  roseau/load_flow/io/dgs/__init__.py
  roseau/load_flow/io/dgs/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_converters.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/typing.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/types.py
Labels: bug
