Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-12, with the labels that each got.

#291 Fix bugs in JSON serialization
  doc/Changelog.md
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/data/README.md
  roseau/load_flow/io/tests/data/generators/v0.py
  roseau/load_flow/io/tests/data/generators/v1.py
  roseau/load_flow/io/tests/data/generators/v2.py
  roseau/load_flow/io/tests/data/network_json_v0.json
  roseau/load_flow/io/tests/data/network_json_v0.py
  roseau/load_flow/io/tests/data/network_json_v1.json
  roseau/load_flow/io/tests/data/network_json_v2.json
  roseau/load_flow/io/tests/test_dict.py
Labels: bug

#293 Update documentation, fix lines and transformers loading
  README.md
  doc/Changelog.md
  doc/index.md
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/tests/test_lines.py
  roseau/load_flow/models/tests/test_transformers.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
Labels: bug, documentation

#295 DOC: Download LFS files to build the documentation on ReadTheDoc
  .readthedocs.yaml
  doc/models/index.md
  doc/usage/index.md
Labels: bug

#301 Improve singular matrix error
  doc/Changelog.md
  roseau/load_flow/exceptions.py
  roseau/load_flow/network.py
Labels: enhancement

#302 De-duplicate the documentation welcome section and fix ipython code-block
  README.md
  doc/Installation.md
  doc/License.md
  doc/index.md
  pyproject.toml
  uv.lock
Labels: bug, documentation

#303 Fix voltage_level network result when missing limits
  doc/Changelog.md
  roseau/load_flow/__init__.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/constants.py
Labels: bug, enhancement

#304 Move important modules to top-level
  .github/workflows/ci.yml
  doc/Changelog.md
  doc/conf.py
  doc/usage/Extras.md
  pyproject.toml
  roseau/load_flow/__init__.py
  roseau/load_flow/_compat.py
  roseau/load_flow/_solvers.py
  roseau/load_flow/_wrapper.py
  roseau/load_flow/conftest.py
  roseau/load_flow/constants.py
  roseau/load_flow/converters.py
  roseau/load_flow/io/dgs/__init__.py
  roseau/load_flow/io/dgs/constants.py
  roseau/load_flow/io/dgs/lines.py
  roseau/load_flow/io/dgs/switches.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_lines.py
  roseau/load_flow/network.py
  roseau/load_flow/plotting.py
  roseau/load_flow/sym.py
  roseau/load_flow/tests/test_converters.py
  roseau/load_flow/tests/test_deprecations.py
  roseau/load_flow/tests/test_sym.py
  roseau/load_flow/tests/test_types.py
  roseau/load_flow/types.py
  roseau/load_flow/units.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/constants.py
  roseau/load_flow/utils/doc_utils.py
  roseau/load_flow/utils/dtypes.py
  roseau/load_flow/utils/exceptions.py
  roseau/load_flow/utils/optional_deps.py
  roseau/load_flow/utils/tests/test_constants.py
  roseau/load_flow/utils/tests/test_optional_deps.py
  roseau/load_flow/utils/tests/test_versions.py
  roseau/load_flow/utils/types.py
  roseau/load_flow/utils/versions.py
Labels: enhancement
