Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-02, with the labels that each got.

#173 Remove conda
  .gitignore
  .pre-commit-config.yaml
  conda/environment.yml
  conda/meta.yaml
  doc/Changelog.md
  doc/Installation.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/license.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
Labels: enhancement

#175 Fix bug when serializing line parameters with numpy values
  doc/Changelog.md
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/transformers/parameters.py
Labels: bug

#178 Merge and deprecate results serialization methods
  .pre-commit-config.yaml
  doc/Changelog.md
  doc/License.md
  doc/usage/Connecting_Elements.md
  doc/usage/Getting_Started.md
  pyproject.toml
  roseau/load_flow/conftest.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/conftest.py
  roseau/load_flow/models/tests/data/Network_1Ph.json
  roseau/load_flow/models/tests/data/Network_3Ph_Balanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced_Shunt.json
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/data/networks/single_phase_network.json
  roseau/load_flow/tests/data/networks/small_network.json
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/mixins.py
  scripts/generate_test_networks.py
Labels: enhancement

#179 Bug in `propagate_potentials` with "center" transformer types
  doc/Changelog.md
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: bug

#180 Version 0.7.0
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  conda/environment.yml
  conda/meta.yaml
  doc/Changelog.md
  doc/Installation.md
  doc/License.md
  doc/conf.py
  doc/usage/Connecting_Elements.md
  doc/usage/Getting_Started.md
  poetry.lock
  pyproject.toml
  roseau/load_flow/_solvers.py
  roseau/load_flow/conftest.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/license.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/conftest.py
  roseau/load_flow/models/tests/data/Network_1Ph.json
  roseau/load_flow/models/tests/data/Network_3Ph_Balanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced_Shunt.json
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/data/networks/single_phase_network.json
  roseau/load_flow/tests/data/networks/small_network.json
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/mixins.py
  scripts/generate_test_networks.py
Labels: bug, enhancement, dependencies

#182 Improve error message when network results do not exist
  doc/Changelog.md
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#184 DOC: Improve metadata and navigation menu
  doc/.htaccess
  doc/Changelog.md
  doc/Installation.md
  doc/License.md
  doc/Solvers.md
  doc/conf.py
  doc/index.md
  doc/models/Bus.md
  doc/models/Ground.md
  doc/models/Line/Parameters.md
  doc/models/Line/ShuntLine.md
  doc/models/Line/SimplifiedLine.md
  doc/models/Line/index.md
  doc/models/Load/CurrentLoad.md
  doc/models/Load/FlexibleLoad/Control.md
  doc/models/Load/FlexibleLoad/FeasibleDomain.md
  doc/models/Load/FlexibleLoad/FlexibleParameter.md
  doc/models/Load/FlexibleLoad/Projection.md
  doc/models/Load/FlexibleLoad/index.md
  doc/models/Load/ImpedanceLoad.md
  doc/models/Load/PowerLoad.md
  doc/models/Load/index.md
  doc/models/PotentialRef.md
  doc/models/Switch.md
  doc/models/Transformer/Center_Tapped_Transformer.md
  doc/models/Transformer/Single_Phase_Transformer.md
  doc/models/Transformer/Three_Phase_Transformer.md
  doc/models/Transformer/index.md
  doc/models/VoltageSource.md
  doc/models/index.md
  doc/robots.txt
  doc/usage/Catalogues.md
  doc/usage/Connecting_Elements.md
  doc/usage/Extras.md
  doc/usage/Flexible_Loads.md
  doc/usage/Getting_Started.md
  doc/usage/Plotting.md
  doc/usage/Short_Circuit.md
  doc/usage/index.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement
