Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2024-08, with the labels that each got.

#249 Accept scalar values as source voltages
  doc/Changelog.md
  doc/models/Bus.md
  doc/models/Ground.md
  doc/models/Line/ShuntLine.md
  doc/models/Line/SimplifiedLine.md
  doc/models/Load/CurrentLoad.md
  doc/models/Load/FlexibleLoad/FeasibleDomain.md
  doc/models/Load/ImpedanceLoad.md
  doc/models/Load/PowerLoad.md
  doc/models/Switch.md
  doc/models/Transformer/Center_Tapped_Transformer.md
  doc/models/Transformer/Single_Phase_Transformer.md
  doc/models/Transformer/Three_Phase_Transformer.md
  doc/models/VoltageSource.md
  doc/usage/Connecting_Elements.md
  doc/usage/Flexible_Loads.md
  doc/usage/Getting_Started.md
  doc/usage/Short_Circuit.md
  roseau/load_flow/io/dgs/sources.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/models/tests/test_sources.py
  roseau/load_flow/tests/test_electrical_network.py
  tutorials/OpenDSS/Tutorial_1/Exercise_1.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-Earth-Return.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-With-Neutral.ipynb
Labels: enhancement

#253 Add testing module
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/tests/test_loads.py
  roseau/load_flow/models/tests/test_sources.py
  roseau/load_flow/testing.py
Labels: enhancement

#255 Update the figures of the documentation
  doc/Changelog.md
  doc/_static/Line/American_Shunt_Line.svg
  doc/_static/Line/American_Simplified_Line.svg
  doc/_static/Line/European_Shunt_Line.svg
  doc/_static/Load/American_Delta_Load.svg
  doc/_static/Load/American_Star_Load.svg
  doc/_static/Load/European_Delta_Load.svg
  doc/_static/Load/European_Star_Load.svg
  doc/_static/VoltageSource/American_Delta_Voltage_Source.svg
  doc/_static/VoltageSource/American_Star_Voltage_Source.svg
  doc/_static/VoltageSource/European_Delta_Voltage_Source.svg
  doc/_static/VoltageSource/European_Star_Voltage_Source.svg
  doc/images/Load/American_Delta_Load.tex
  doc/images/Load/American_Star_Load.tex
  doc/images/Load/European_Delta_Load.tex
  doc/images/Load/European_Star_Load.tex
  doc/images/Makefile
  doc/images/Preambule.tex
  doc/images/VoltageSource/American_Delta_Voltage_Source.tex
  doc/images/VoltageSource/American_Star_Voltage_Source.tex
  doc/images/VoltageSource/European_Delta_Voltage_Source.tex
  doc/images/VoltageSource/European_Star_Voltage_Source.tex
Labels: documentation

#257 Add `from_coiffier_model` method to line parameters
  doc/Changelog.md
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
Labels: enhancement

#258 Add plotting module and advanced documentation
  .vscode/cspell.json
  doc/Changelog.md
  doc/_static/Advanced/Floating_Neutral_Auto.png
  doc/_static/Advanced/Floating_Neutral_Manual.png
  doc/_static/Advanced/Goldstein_And_Price.svg
  doc/_static/Plotting/MVFeeder210.html
  doc/_static/Plotting/Plot_Voltage_Phasors.png
  doc/_static/css/custom.css
  doc/advanced/Floating_Neutral.md
  doc/advanced/Potential_Reference.md
  doc/advanced/Solvers.md
  doc/advanced/index.md
  doc/conf.py
  doc/index.md
  doc/models/PotentialRef.md
  doc/usage/Plotting.md
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/network.py
  roseau/load_flow/plotting.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/typing.py
  roseau/load_flow/units.py
  scripts/plot_network_catalogue.py
Labels: documentation, enhancement

#259 Invalidate the license cache
  doc/Changelog.md
  roseau/load_flow/license.py
Labels: bug

#261 Document plotting networks without geometries using networkx
  doc/Changelog.md
  doc/advanced/Potential_Reference.md
  doc/usage/Plotting.md
Labels: documentation

#262 Error when transformer has null impedance
  doc/Changelog.md
  roseau/load_flow/exceptions.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
Labels: enhancement
