Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2025-01, with the labels that each got.

#306 Add missing information and improve performance
  doc/Changelog.md
  doc/models/Bus.md
  doc/models/Line/ShuntLine.md
  doc/models/Line/SimplifiedLine.md
  doc/models/Load/CurrentLoad.md
  doc/models/Load/FlexibleLoad/FeasibleDomain.md
  doc/models/Load/ImpedanceLoad.md
  doc/models/Load/PowerLoad.md
  doc/models/Switch.md
  doc/models/Transformer/Single_Phase_Transformer.md
  doc/usage/Connecting_Elements.md
  doc/usage/Getting_Started.md
  doc/usage/Short_Circuit.md
  pyproject.toml
  roseau/load_flow/io/dgs/sources.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/helpers.py
  roseau/load_flow/utils/mixins.py
  scripts/generate_test_networks.py
  uv.lock
Labels: enhancement

#307 Make violations of lines and buses per-phase
  doc/Changelog.md
  doc/usage/Getting_Started.md
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/models/tests/test_lines.py
  roseau/load_flow/typing.py
  roseau/load_flow/utils/doc_utils.py
Labels: enhancement

#309 Remove the tutorials
  tutorials/OpenDSS/README.md
  tutorials/OpenDSS/Tutorial_1/Exercise_1.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-Earth-Return.ipynb
  tutorials/OpenDSS/Tutorial_2/Tutorial-DERHC-1-With-Neutral.ipynb
  tutorials/OpenDSS/images/LV_Network_With_Neutral.png
  tutorials/OpenDSS/images/LV_Network_Without_Neutral.png
  tutorials/OpenDSS/images/Star_Delta.png
  tutorials/OpenDSS/pyproject.toml
  tutorials/README.md
Labels: documentation

#310 Support star and zigzag transformers with non brought out neutrals
  doc/Changelog.md
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/data/generators/v3.py
  roseau/load_flow/io/tests/data/network_json_v0.py
  roseau/load_flow/io/tests/data/network_json_v3.json
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/tests/test_transformers.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/testing.py
Labels: bug

#311 Improve line enumeration types and fix errors in Coiffier's model
  doc/Changelog.md
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/tests/test_line_parameters.py
  roseau/load_flow/tests/test_types.py
  roseau/load_flow/types.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/helpers.py
Labels: bug, enhancement

#312 DOC: RTD generates sitemap
  .pre-commit-config.yaml
  doc/conf.py
  pyproject.toml
  uv.lock
Labels: documentation

#316 Centralize the low-level solver code
  roseau/load_flow/_solvers.py
  roseau/load_flow/network.py
Labels: enhancement

#317 Fix the vector group regex for rlfs
  .pre-commit-config.yaml
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  scripts/update_catalogue_networks.py
Labels: enhancement

#318 Implement more transformer vector groups
  .vscode/tasks.json
  doc/Changelog.md
  doc/_static/Transformer/Additional_Connections.svg
  doc/_static/Transformer/Common_Connections.svg
  doc/images/Makefile
  doc/images/Transformer/Additional_Connections.tex
  doc/images/Transformer/Common_Connections.tex
  doc/images/Transformer/Connection_Defs.tex
  doc/models/Transformer/Three_Phase_Transformer.md
  doc/models/Transformer/index.md
  doc/usage/Data_Exchange.md
  roseau/load_flow/constants.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
Labels: enhancement

#319 Use HV and LV for transformers instead of primary and secondary
  doc/Changelog.md
  doc/advanced/Potential_Reference.md
  doc/models/Transformer/Center_Tapped_Transformer.md
  doc/models/Transformer/Single_Phase_Transformer.md
  doc/models/Transformer/Three_Phase_Transformer.md
  doc/usage/Data_Exchange.md
  doc/usage/Flexible_Loads.md
  roseau/load_flow/io/dgs/transformers.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/data/network_json_v0.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/core.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/switches.py
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/models/tests/test_phases.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/tests/test_transformers.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/__init__.py
  roseau/load_flow/utils/deprecations.py
  roseau/load_flow/utils/tests/test_deprecations.py
  scripts/generate_test_networks.py
  scripts/generate_transformer_parameters_catalogue.py
  scripts/update_catalogue_networks.py
Labels: enhancement

#320 Update the JSON format of transformers
  roseau/load_flow/data/networks/LVFeeder00939_Summer.json
  roseau/load_flow/data/networks/LVFeeder00939_Winter.json
  roseau/load_flow/data/networks/LVFeeder02639_Summer.json
  roseau/load_flow/data/networks/LVFeeder02639_Winter.json
  roseau/load_flow/data/networks/LVFeeder04790_Summer.json
  roseau/load_flow/data/networks/LVFeeder04790_Winter.json
  roseau/load_flow/data/networks/LVFeeder06713_Summer.json
  roseau/load_flow/data/networks/LVFeeder06713_Winter.json
  roseau/load_flow/data/networks/LVFeeder06926_Summer.json
  roseau/load_flow/data/networks/LVFeeder06926_Winter.json
  roseau/load_flow/data/networks/LVFeeder06975_Summer.json
  roseau/load_flow/data/networks/LVFeeder06975_Winter.json
  roseau/load_flow/data/networks/LVFeeder18498_Summer.json
  roseau/load_flow/data/networks/LVFeeder18498_Winter.json
  roseau/load_flow/data/networks/LVFeeder18769_Summer.json
  roseau/load_flow/data/networks/LVFeeder18769_Winter.json
  roseau/load_flow/data/networks/LVFeeder19558_Summer.json
  roseau/load_flow/data/networks/LVFeeder19558_Winter.json
  roseau/load_flow/data/networks/LVFeeder20256_Summer.json
  roseau/load_flow/data/networks/LVFeeder20256_Winter.json
  roseau/load_flow/data/networks/LVFeeder23832_Summer.json
  roseau/load_flow/data/networks/LVFeeder23832_Winter.json
  roseau/load_flow/data/networks/LVFeeder24400_Summer.json
  roseau/load_flow/data/networks/LVFeeder24400_Winter.json
  roseau/load_flow/data/networks/LVFeeder27429_Summer.json
  roseau/load_flow/data/networks/LVFeeder27429_Winter.json
  roseau/load_flow/data/networks/LVFeeder27681_Summer.json
  roseau/load_flow/data/networks/LVFeeder27681_Winter.json
  roseau/load_flow/data/networks/LVFeeder30216_Summer.json
  roseau/load_flow/data/networks/LVFeeder30216_Winter.json
  roseau/load_flow/data/networks/LVFeeder31441_Summer.json
  roseau/load_flow/data/networks/LVFeeder31441_Winter.json
  roseau/load_flow/data/networks/LVFeeder36284_Summer.json
  roseau/load_flow/data/networks/LVFeeder36284_Winter.json
  roseau/load_flow/data/networks/LVFeeder36360_Summer.json
  roseau/load_flow/data/networks/LVFeeder36360_Winter.json
  roseau/load_flow/data/networks/LVFeeder37263_Summer.json
  roseau/load_flow/data/networks/LVFeeder37263_Winter.json
  roseau/load_flow/data/networks/LVFeeder38211_Summer.json
  roseau/load_flow/data/networks/LVFeeder38211_Winter.json
  roseau/load_flow/io/dict.py
  roseau/load_flow/models/loads/loads.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/tests/data/networks/all_element_network.json
  roseau/load_flow/tests/test_electrical_network.py
Labels: enhancement

#321 Add transformer results aliases and rename dataframes columns
  doc/Changelog.md
  doc/models/Transformer/Center_Tapped_Transformer.md
  doc/models/Transformer/Single_Phase_Transformer.md
  doc/models/Transformer/Three_Phase_Transformer.md
  roseau/load_flow/models/tests/test_transformers.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow/utils/dtypes.py
Labels: enhancement

#322 Add experimental namespace package `roseau.load_flow_single`
  .gitignore
  .vscode/cspell.json
  doc/conf.py
  pyproject.toml
  roseau/load_flow_single/README.md
  roseau/load_flow_single/__init__.py
  roseau/load_flow_single/conftest.py
  roseau/load_flow_single/io/__init__.py
  roseau/load_flow_single/io/dict.py
  roseau/load_flow_single/io/tests/__init__.py
  roseau/load_flow_single/io/tests/data/generators/v3.py
  roseau/load_flow_single/io/tests/data/network_json_v3.json
  roseau/load_flow_single/io/tests/data/network_json_v3.py
  roseau/load_flow_single/io/tests/test_dict.py
  roseau/load_flow_single/models/__init__.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/buses.py
  roseau/load_flow_single/models/core.py
  roseau/load_flow_single/models/flexible_parameters.py
  roseau/load_flow_single/models/line_parameters.py
  roseau/load_flow_single/models/lines.py
  roseau/load_flow_single/models/loads.py
  roseau/load_flow_single/models/sources.py
  roseau/load_flow_single/models/switches.py
  roseau/load_flow_single/models/tests/__init__.py
  roseau/load_flow_single/models/tests/conftest.py
  roseau/load_flow_single/models/tests/data/small_network.json
  roseau/load_flow_single/models/tests/data/small_shunt_network.json
  roseau/load_flow_single/models/tests/test_branches.py
  roseau/load_flow_single/models/tests/test_buses.py
  roseau/load_flow_single/models/tests/test_element.py
  roseau/load_flow_single/models/tests/test_flexible_parameters.py
  roseau/load_flow_single/models/tests/test_line_parameters.py
  roseau/load_flow_single/models/tests/test_lines.py
  roseau/load_flow_single/models/tests/test_loads.py
  roseau/load_flow_single/models/tests/test_sources.py
  roseau/load_flow_single/models/tests/test_switches.py
  roseau/load_flow_single/models/tests/test_transformers.py
  roseau/load_flow_single/models/transformer_parameters.py
  roseau/load_flow_single/models/transformers.py
  roseau/load_flow_single/network.py
  roseau/load_flow_single/tests/__init__.py
  roseau/load_flow_single/tests/data/networks/all_elements_network.json
  roseau/load_flow_single/tests/data/networks/small_network.json
  roseau/load_flow_single/tests/test_electrical_network.py
  roseau/load_flow_single/tests/test_import.py
  scripts/generate_single_test_networks.py
Labels: enhancement

#326 Rename `Bus.potentials` to `Bus.initial_potentials`
  doc/Changelog.md
  roseau/load_flow/io/dict.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/tests/data/Network_1Ph.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced_Shunt.json
  roseau/load_flow/models/tests/test_buses.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/data/networks/all_element_network.json
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow_single/models/transformers.py
  scripts/generate_test_networks.py
Labels: enhancement
