Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2025-03, with the labels that each got.

#343 Warn when a line or a switch connects buses with different nominal voltages
  doc/Changelog.md
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/switches.py
  roseau/load_flow/models/tests/test_branches.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/lines.py
  roseau/load_flow_single/models/switches.py
  roseau/load_flow_single/models/tests/test_lines.py
  roseau/load_flow_single/models/tests/test_switches.py
Labels: enhancement

#345 Remove the transformer specific results
  roseau/load_flow/models/tests/test_transformers.py
  roseau/load_flow/models/transformers/transformers.py
  roseau/load_flow_single/models/tests/test_transformers.py
  roseau/load_flow_single/models/transformers.py
Labels: enhancement

#342 Add DGS import/export to load_flow_single
  roseau/load_flow/io/dgs/loads.py
  roseau/load_flow/io/dgs/utils.py
  roseau/load_flow/testing.py
  roseau/load_flow/tests/test_testing.py
  roseau/load_flow_single/conftest.py
  roseau/load_flow_single/io/__init__.py
  roseau/load_flow_single/io/common.py
  roseau/load_flow_single/io/dgs/__init__.py
  roseau/load_flow_single/io/dgs/buses.py
  roseau/load_flow_single/io/dgs/lines.py
  roseau/load_flow_single/io/dgs/loads.py
  roseau/load_flow_single/io/dgs/pwf.py
  roseau/load_flow_single/io/dgs/sources.py
  roseau/load_flow_single/io/dgs/switches.py
  roseau/load_flow_single/io/dgs/transformers.py
  roseau/load_flow_single/io/tests/test_dgs.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/buses.py
  roseau/load_flow_single/models/core.py
  roseau/load_flow_single/models/line_parameters.py
  roseau/load_flow_single/models/lines.py
  roseau/load_flow_single/network.py
Labels: enhancement

#347 [single] Fix segfault when adding a shunt line to existing network
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/lines.py
  roseau/load_flow_single/models/switches.py
  roseau/load_flow_single/models/transformers.py
  roseau/load_flow_single/tests/test_electrical_network.py
Labels: bug, single

#350 Fix invalid transformer params with no leakage reactance
  doc/Changelog.md
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
Labels: bug

#351 Improve the support of the network CRS
  doc/Changelog.md
  roseau/load_flow/io/common.py
  roseau/load_flow/io/dgs/__init__.py
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/network.py
  roseau/load_flow/typing.py
  roseau/load_flow_single/io/common.py
  roseau/load_flow_single/io/dgs/__init__.py
  roseau/load_flow_single/io/dict.py
  roseau/load_flow_single/network.py
Labels: bug, enhancement

#355 Add HV/MV transformer models to the catalogue
  doc/Changelog.md
  doc/_static/Transformer/References/2025_03_14_SCOTECH_S11-30MVA-132-11KV.pdf
  doc/_static/Transformer/References/2025_03_14_SCOTECH_SC-S-100MVA-220-35KV.pdf
  doc/_static/Transformer/References/2025_03_14_SCOTECH_SFZ11-25MVA-33-11KV.pdf
  doc/_static/Transformer/References/2025_03_14_SCOTECH_SZ11-76MVA-110-35 kV.pdf
  doc/usage/Catalogues.md
  roseau/load_flow/data/transformers/Catalogue.csv
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
Labels: enhancement

#358 Fix in DGS export
  doc/Changelog.md
  pyproject.toml
  roseau/load_flow/__about__.py
  roseau/load_flow_single/io/dgs/loads.py
Labels: bug
