Repository RoseauTechnologies/Roseau_Load_Flow, pull requests merged in 2025-04, with the labels that each got.

#360 BUG: ground not added by `add_short_circuit`
  doc/Changelog.md
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/tests/test_buses.py
Labels: bug

#362 Drop support for Python 3.10
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  doc/Changelog.md
  doc/index.md
  pyproject.toml
  roseau/load_flow/_compat.py
  roseau/load_flow/exceptions.py
  roseau/load_flow/io/dgs/utils.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/buses.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/parameters.py
  roseau/load_flow/models/loads/flexible_parameters.py
  roseau/load_flow/models/potential_refs.py
  roseau/load_flow/models/sources.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/network.py
  roseau/load_flow/tests/test_license.py
  roseau/load_flow/utils/helpers.py
  roseau/load_flow/utils/mixins.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/buses.py
  roseau/load_flow_single/models/flexible_parameters.py
  roseau/load_flow_single/models/line_parameters.py
  roseau/load_flow_single/models/sources.py
  roseau/load_flow_single/network.py
  roseau/load_flow_single/tests/test_import.py
  uv.lock
Labels: enhancement

#365 Fix minor inconsistency in sc parameters calculation of transformers
  doc/Changelog.md
  roseau/load_flow/models/transformers/parameters.py
Labels: bug

#366 Improve the transformer parameters and the catalogue
  doc/Changelog.md
  doc/usage/Catalogues.md
  roseau/load_flow/__init__.py
  roseau/load_flow/data/transformers/Catalogue.csv
  roseau/load_flow/io/dgs/transformers.py
  roseau/load_flow/models/tests/test_transformer_parameters.py
  roseau/load_flow/models/transformers/parameters.py
  roseau/load_flow/types.py
  roseau/load_flow/utils/doc_utils.py
  roseau/load_flow/utils/helpers.py
  roseau/load_flow_single/__init__.py
  roseau/load_flow_single/io/dgs/transformers.py
Labels: enhancement

#367 [single] Return scalar results as Python objects
  roseau/load_flow/models/grounds.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/connectables.py
  roseau/load_flow_single/models/terminals.py
Labels: enhancement, single

#370 Add debuging methods to the solver
  roseau/load_flow/_solvers.py
Labels: enhancement

#369 Add results of ground potential to shunt line
  doc/Changelog.md
  doc/models/Line/ShuntLine.md
  roseau/load_flow/io/dict.py
  roseau/load_flow/io/tests/data/generators/v4.py
  roseau/load_flow/io/tests/data/network_json_v4.json
  roseau/load_flow/io/tests/test_dict.py
  roseau/load_flow/models/branches.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow/models/lines/lines.py
  roseau/load_flow/models/tests/data/Network_1Ph.json
  roseau/load_flow/models/tests/data/Network_3Ph_Balanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced.json
  roseau/load_flow/models/tests/data/Network_3Ph_Unbalanced_Shunt.json
  roseau/load_flow/models/tests/test_element.py
  roseau/load_flow/models/tests/test_lines.py
  roseau/load_flow/tests/data/networks/all_element_network.json
  roseau/load_flow/tests/data/networks/single_phase_network.json
  roseau/load_flow/tests/data/networks/small_network.json
  roseau/load_flow/tests/test_electrical_network.py
  roseau/load_flow_single/io/dict.py
  roseau/load_flow_single/io/tests/data/generators/v4.py
  roseau/load_flow_single/io/tests/data/network_json_v4.json
  roseau/load_flow_single/io/tests/test_dict.py
Labels: enhancement

#371 Deprecate forgotten transformer properties from last release
  doc/Changelog.md
  roseau/load_flow/models/transformers/transformers.py
Labels: enhancement

#372 [single] Performance improvements
  roseau/load_flow/models/core.py
  roseau/load_flow/models/grounds.py
  roseau/load_flow_single/models/branches.py
  roseau/load_flow_single/models/buses.py
  roseau/load_flow_single/models/connectables.py
  roseau/load_flow_single/models/core.py
  roseau/load_flow_single/models/line_parameters.py
  roseau/load_flow_single/models/loads.py
  roseau/load_flow_single/models/terminals.py
  roseau/load_flow_single/network.py
Labels: enhancement
